# -*- coding: utf-8 -*-
"""Task 7.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yobOAPPAQxUOieBEZK62GVyRZasKqPTJ
"""

import sqlite3
import pandas as pd
import matplotlib.pyplot as plt

# 1. CONNECT DATABASE
conn = sqlite3.connect("/sales data.db")

# 2. RUN SQL QUERY (total quantity + revenue per product)
query = """
SELECT
    product,
    SUM(quantity) AS total_qty,
    SUM(quantity * price) AS revenue
FROM sales
GROUP BY product
"""
df = pd.read_sql_query(query, conn)

print("Sales Summary:")
print(df)

# 3. PLOT BAR CHART
df.plot(kind='bar', x='product', y='revenue')
plt.title("Revenue by Product")
plt.xlabel("Product")
plt.ylabel("Revenue")
plt.tight_layout()

# save chart
plt.savefig("sales_chart.png")
plt.show()

conn.close()